apiVersion: v1
kind: Pod
metadata:
  name: my-pod-mount-cm
spec:
  containers:
    
    - name: busybox
      image: busybox
      resources:
        # Requests are what the container is guaranteed to get. (minimum)
        requests:
          memory: "50Mi"
          cpu: "100m"
        # Limits make sure a container never goes above a certain value. (maximum)
        limits:
          memory: "200Mi"
          cpu: "500m"
      command:
      - sleep
      - "3600"
      volumeMounts:
      - name: my-config-volume
        mountPath: /app/config
  volumes:
    - name: my-config-volume
      configMap:
        name: my-config-map
  restartPolicy: Never
