apiVersion: v1
kind: Pod
metadata:
  name: my-pod-mount-env
spec:
  containers:
    - name: busybox
      image: busybox
      resources:
        # Requests are what the container is guaranteed to get. (minimum)
        requests:
          memory: "50Mi"
          cpu: "100m"
        # Limits make sure a container never goes above a certain value. (maximum)
        limits:
          memory: "200Mi"
          cpu: "500m"
      command:
      - sleep
      - "3600"
      env:
        - name: MY_PASSWORD_VARIABLE
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: dbpass
  restartPolicy: Never
