apiVersion: v1
kind: Pod
metadata:
  name: myApp
spec:
  containers:
  - name: my-app
    image: mydockername
    command: ["run"]
    resources:
      # Requests are what the container is guaranteed to get. (minimum)
      requests:
        memory: "50Mi"
        cpu: "100m"
      # Limits make sure a container never goes above a certain value. (maximum)
      limits:
        memory: "200Mi"
        cpu: "500m"
  # define init containers that should be executed before the main containers start
  initContainers:
  - name: init-before
    image: busybox
    command: ['sh', '-c', 'until nslookup config-service; do echo config-service not up; sleep 2; done;']  
