apiVersion: v1
kind: Pod
metadata:
  name: my-pod

spec:
  containers:

  - name: busybox
    image: busybox
    resources:
        # Requests are what the container is guaranteed to get. (minimum)
        requests:
          memory: "50Mi"
          cpu: "100m"
        # Limits make sure a container never goes above a certain value. (maximum)
        limits:
          memory: "200Mi"
          cpu: "500m"
    volumeMounts:
    - name: config-volume
      mountPath: /shared-config

  - name: busybox2
    image: busybox
    resources:
        # Requests are what the container is guaranteed to get. (minimum)
        requests:
          memory: "50Mi"
          cpu: "100m"
        # Limits make sure a container never goes above a certain value. (maximum)
        limits:
          memory: "200Mi"
          cpu: "500m"
    volumeMounts:
    - name: config-volume
      mountPath: /myconfig
  volumes:
  - name: config-volume
    emptyDir: {}