apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  volumes:
    - name: my-pv
      persistentVolumeClaim:
        claimName: my-pv-claim
  containers:
    - name: my-container
      image: busybox
      resources:
        # Requests are what the container is guaranteed to get. (minimum)
        requests:
          memory: "50Mi"
          cpu: "100m"
        # Limits make sure a container never goes above a certain value. (maximum)
        limits:
          memory: "200Mi"
          cpu: "500m"
      volumeMounts:
        - mountPath: "/usr/data"
          name: my-pv