apiVersion: batch/v1
kind: CronJob
metadata:
  name: hello
spec:
  schedule: "0 1 * * *"
  jobTemplate:
    spec:
      # by using the "parallelism", we could define the number of replicas of the job
      parallelism: 3
      template:
        spec:
          containers:
           - name: run-job
             image: node:lts-jessie
             command: ["node", “job.js”]
          restartPolicy: OnFailure
